apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cvsm
  namespace: cvsm
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [api.calvery.xyz, calvery.xyz]
      secretName: cvsm-tls
  rules:
    - host: api.calvery.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cvsm-api
                port: { number: 80 }
    - host: calvery.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cvsm-web
                port: { number: 80 }
